apiVersion: eevee.bot/v1alpha1
kind: Toolbox
metadata:
  name: toolbox-sample
spec:
  # Number of toolboxe replicas to deploy
  size: 1

  # Override container image
  # containerImage: ghcr.io/eeveebot/toolbox:latest

  # Override pull policy
  # Defaults to IfNotPresent
  # pullPolicy: Always
