apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: eevee
    app.kubernetes.io/name: eevee-operator
    app.kubernetes.io/managed-by: kustomize
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eevee-operator
  namespace: system
  labels:
    control-plane: eevee
    app.kubernetes.io/name: eevee-operator
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      control-plane: eevee
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: operator
      labels:
        control-plane: eevee
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                    - amd64
                    - arm64
                - key: kubernetes.io/os
                  operator: In
                  values:
                    - linux
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - command:
        - /operator
        args:
          - --leader-elect
          - --health-probe-bind-address=:8081
        image: ghcr.io/eeveebot/operator:latest
        imagePullPolicy: "Always"
        name: operator
        env:
          - name: DEFAULT_TOOLBOX_IMAGE
            value: ghcr.io/eeveebot/toolbox:latest
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 2000m
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 64Mi
      serviceAccountName: eevee-operator
      terminationGracePeriodSeconds: 10
