//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectorIrc) DeepCopyInto(out *ConnectorIrc) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectorIrc.
func (in *ConnectorIrc) DeepCopy() *ConnectorIrc {
	if in == nil {
		return nil
	}
	out := new(ConnectorIrc)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConnectorIrc) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectorIrcList) DeepCopyInto(out *ConnectorIrcList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ConnectorIrc, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectorIrcList.
func (in *ConnectorIrcList) DeepCopy() *ConnectorIrcList {
	if in == nil {
		return nil
	}
	out := new(ConnectorIrcList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConnectorIrcList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectorIrcSpec) DeepCopyInto(out *ConnectorIrcSpec) {
	*out = *in
	if in.Connections != nil {
		in, out := &in.Connections, &out.Connections
		*out = make([]IrcConnectionSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectorIrcSpec.
func (in *ConnectorIrcSpec) DeepCopy() *ConnectorIrcSpec {
	if in == nil {
		return nil
	}
	out := new(ConnectorIrcSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectorIrcStatus) DeepCopyInto(out *ConnectorIrcStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectorIrcStatus.
func (in *ConnectorIrcStatus) DeepCopy() *ConnectorIrcStatus {
	if in == nil {
		return nil
	}
	out := new(ConnectorIrcStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IRCServerConnectionSpec) DeepCopyInto(out *IRCServerConnectionSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IRCServerConnectionSpec.
func (in *IRCServerConnectionSpec) DeepCopy() *IRCServerConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(IRCServerConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentSpec) DeepCopyInto(out *IdentSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentSpec.
func (in *IdentSpec) DeepCopy() *IdentSpec {
	if in == nil {
		return nil
	}
	out := new(IdentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IrcConnectionSpec) DeepCopyInto(out *IrcConnectionSpec) {
	*out = *in
	out.IRCSpec = in.IRCSpec
	out.Ident = in.Ident
	in.PostConnect.DeepCopyInto(&out.PostConnect)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IrcConnectionSpec.
func (in *IrcConnectionSpec) DeepCopy() *IrcConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(IrcConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostConnectJoinSpec) DeepCopyInto(out *PostConnectJoinSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostConnectJoinSpec.
func (in *PostConnectJoinSpec) DeepCopy() *PostConnectJoinSpec {
	if in == nil {
		return nil
	}
	out := new(PostConnectJoinSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostConnectMessageSpec) DeepCopyInto(out *PostConnectMessageSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostConnectMessageSpec.
func (in *PostConnectMessageSpec) DeepCopy() *PostConnectMessageSpec {
	if in == nil {
		return nil
	}
	out := new(PostConnectMessageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostConnectModeSpec) DeepCopyInto(out *PostConnectModeSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostConnectModeSpec.
func (in *PostConnectModeSpec) DeepCopy() *PostConnectModeSpec {
	if in == nil {
		return nil
	}
	out := new(PostConnectModeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostConnectRawSpec) DeepCopyInto(out *PostConnectRawSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostConnectRawSpec.
func (in *PostConnectRawSpec) DeepCopy() *PostConnectRawSpec {
	if in == nil {
		return nil
	}
	out := new(PostConnectRawSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostConnectSpec) DeepCopyInto(out *PostConnectSpec) {
	*out = *in
	if in.Join != nil {
		in, out := &in.Join, &out.Join
		*out = make([]PostConnectJoinSpec, len(*in))
		copy(*out, *in)
	}
	if in.Message != nil {
		in, out := &in.Message, &out.Message
		*out = make([]PostConnectMessageSpec, len(*in))
		copy(*out, *in)
	}
	if in.Mode != nil {
		in, out := &in.Mode, &out.Mode
		*out = make([]PostConnectModeSpec, len(*in))
		copy(*out, *in)
	}
	if in.Raw != nil {
		in, out := &in.Raw, &out.Raw
		*out = make([]PostConnectRawSpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostConnectSpec.
func (in *PostConnectSpec) DeepCopy() *PostConnectSpec {
	if in == nil {
		return nil
	}
	out := new(PostConnectSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Toolbox) DeepCopyInto(out *Toolbox) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Toolbox.
func (in *Toolbox) DeepCopy() *Toolbox {
	if in == nil {
		return nil
	}
	out := new(Toolbox)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Toolbox) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolboxList) DeepCopyInto(out *ToolboxList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Toolbox, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolboxList.
func (in *ToolboxList) DeepCopy() *ToolboxList {
	if in == nil {
		return nil
	}
	out := new(ToolboxList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ToolboxList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolboxSpec) DeepCopyInto(out *ToolboxSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolboxSpec.
func (in *ToolboxSpec) DeepCopy() *ToolboxSpec {
	if in == nil {
		return nil
	}
	out := new(ToolboxSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolboxStatus) DeepCopyInto(out *ToolboxStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolboxStatus.
func (in *ToolboxStatus) DeepCopy() *ToolboxStatus {
	if in == nil {
		return nil
	}
	out := new(ToolboxStatus)
	in.DeepCopyInto(out)
	return out
}
