apiVersion: eevee.bot/v1alpha1
kind: NatsCluster
metadata:
  name: nats-cluster
  namespace: my-eevee-bot
spec:
  #
  # See https://artifacthub.io/packages/helm/nats/nats for full configuration options
  #
  namespaceOverride: my-eevee-bot
  container:
    env:
      # Different from k8s units, suffix must be B, KiB, MiB, GiB, or TiB
      # Should be ~80% of memory limit
      GOMEMLIMIT: 3.5GiB
      TOKEN:
        valueFrom:
          secretKeyRef:
            name: nats-auth
            key: token
    merge:
      resources:
        requests:
          cpu: "2"
          memory: 4Gi
        limits:
          cpu: "2"
          memory: 4Gi
  config:
    cluster:
      enabled: true
      port: 6222
      # must be 2 or higher when jetstream is enabled
      replicas: 3

    jetstream:
      enabled: true
      fileStore:
        enabled: true
        dir: /data
        pvc:
          enabled: true
          size: 10Gi
          storageClassName: mystorageclass
      memoryStore:
        enabled: false
    nats:
      port: 4222

    leafnodes:
      enabled: false

    websocket:
      enabled: false

    mqtt:
      enabled: false

    gateway:
      enabled: false

    monitor:
      enabled: true
      port: 8222

    profiling:
      enabled: false
      port: 65432

    resolver:
      enabled: false

    merge:
      authorization:
        token: << $TOKEN >>
    patch: []

  reloader:
    enabled: true

  promExporter:
    enabled: true
    podMonitor:
      enabled: true

  service:
    enabled: true
    ports:
      nats:
        enabled: true
      leafnodes:
        enabled: true
      websocket:
        enabled: true
      mqtt:
        enabled: true
      cluster:
        enabled: true
      gateway:
        enabled: true
      monitor:
        enabled: true
      profiling:
        enabled: true

  # pod disruption budget
  podDisruptionBudget:
    enabled: true

  # service account
  serviceAccount:
    enabled: true

  natsBox:
    enabled: false # eevee-toolbox has NATS client included
