# permissions for end users to edit toolboxes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: eevee
    app.kubernetes.io/managed-by: kustomize
  name: toolbox-editor-role
rules:
- apiGroups:
  - eevee.bot
  resources:
  - toolboxes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - eevee.bot
  resources:
  - toolboxes/status
  verbs:
  - get
