apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: eevee
    app.kubernetes.io/managed-by: kustomize
  name: eevee-operator-leader-election-rolebinding
  namespace: eevee-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: eevee-operator-leader-election-role
subjects:
- kind: ServiceAccount
  name: eevee-operator
  namespace: eevee-system
