apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eevee-operator-metrics-auth-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: eevee-operator-metrics-auth-role
subjects:
- kind: ServiceAccount
  name: eevee-operator
  namespace: eevee-system
