---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eevee-operator-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - eevee.bot
  resources:
  - connectorircs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - eevee.bot
  resources:
  - connectorircs/finalizers
  verbs:
  - update
- apiGroups:
  - eevee.bot
  resources:
  - connectorircs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - eevee.bot
  resources:
  - toolboxes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - eevee.bot
  resources:
  - toolboxes/finalizers
  verbs:
  - update
- apiGroups:
  - eevee.bot
  resources:
  - toolboxes/status
  verbs:
  - get
  - patch
  - update
