name: Build Operator Image

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  packages: write

concurrency:
  group: "operator"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup Go 1.23.3
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.3"

      - name: Build manifests
        run: |
          cd src/eevee
          make manifests
          make build-installer

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}
          # tag with latest (only on default branch)
          #          <branch>
          #          <pr #>
          #          <hash>
          #          <git tag>
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=sha,format=long
            type=raw,value=latest,priority=900,enable={{is_default_branch}}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: src/eevee
          file: "src/eevee/Dockerfile"
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: install.yaml
          path: src/eevee/dist/install.yaml
